services:
  db:
    image: postgres:15 # Use a specific version of Postgres
    container_name: adk_db
    environment:
      POSTGRES_DB: adk_db # Database name
      POSTGRES_USER: adk_user # Database user
      POSTGRES_PASSWORD: adk_password # Database password
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432 (to avoid conflict with local DB)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adk_user -d adk_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  local-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adk-agent
    ports:
      - "8001:8001"
    environment:
      SESSION_DB_URL: postgresql+psycopg2://adk_user:adk_password@db:5432/adk_db
      GOOGLE_GENAI_USE_VERTEXAI: FALSE
      AGENT_DIR: agents/adk
      REPO_ROOT: /repos
    env_file:
      - .env
    volumes:
      - ~/Solutions:/repos #UPDATE THIS TO YOUR LOCAL DIRECTORIES 
      - type: bind
        source: ${APPDATA:-~/.config}/gcloud
        target: /root/.config/gcloud
        read_only: true
    stdin_open: true 
    tty: true
volumes:
  postgres_data: