services:
  local-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adk-agent
    ports:
      - "8001:8001"
    env_file:
      - .env
    stdin_open: true 
    tty: true
    volumes:
      - ~/Solutions:/repos