include:
  - docker-compose-db.yml

services:
  local-adk-agent:
    extends:
      file: docker-compose-adk.yml
      service: local-adk-agent
    volumes:
      - /home/user/repos:/repos #Update this to mount your local directories
    environment:
      GOOGLE_GENAI_USE_VERTEXAI: "TRUE"
      GOOGLE_CLOUD_PROJECT: ds-staff-gen-ai-prd-955b
      GOOGLE_CLOUD_LOCATION: us-central1

  streamlit-frontend:
    extends:
      file: docker-compose-streamlit.yml
      service: streamlit-frontend
    volumes:
      - ./apps/frontends/streamlit:/app # Mount the Streamlit application code
