services:
  db:
    image: postgres:15 # Use a specific version of Postgres
    container_name: adk_db
    environment:
      POSTGRES_DB: adk_db # Database name
      POSTGRES_USER: adk_user # Database user
      POSTGRES_PASSWORD: adk_password # Database password
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432 (to avoid conflict with local DB)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adk_user -d adk_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  pydantic-ai-db:
    image: postgres:15
    container_name: pydantic_ai_db
    environment:
      POSTGRES_DB: pydantic_ai_db
      POSTGRES_USER: pydantic_ai_user
      POSTGRES_PASSWORD: pydantic_ai_password
    ports:
      - "5434:5432"  # Different port to avoid conflict with ADK DB
    volumes:
      - pydantic_ai_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pydantic_ai_user -d pydantic_ai_db"]
      interval: 10s
      timeout: 5s
      retries: 5  
      
volumes:
  postgres_data:
  pydantic_ai_postgres_data: