services:
  local-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adk-agent
    ports:
      - "8001:8001"
    environment:
      SESSION_DB_URL: postgresql+psycopg2://adk_user:adk_password@db:5432/adk_db
      AGENT_DIR: agents/adk
      REPO_ROOT: /repos
    env_file:
      - .env
    volumes:
      - ~/Solutions:/repos #UPDATE THIS TO YOUR LOCAL DIRECTORIES 
      - type: bind
        source: ${APPDATA:-~/.config}/gcloud
        target: /root/.config/gcloud
        read_only: true
    stdin_open: true 
    tty: true