version: '3.8'

services:
  streamlit-frontend:
    build:
      context: ./apps/frontends/streamlit
      dockerfile: Dockerfile
    container_name: streamlit-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./apps/frontends/streamlit:/app # Mount the Streamlit application code
    environment:
      ADK_BACKEND_URL: http://local-adk-agent:8001 # URL for the ADK backend service within Docker network
      PYTHONUNBUFFERED: 1
    depends_on:
      - local-adk-agent # Ensure ADK backend starts before Streamlit frontend