include:
  - docker-compose-db.yml

services:
  local-adk-agent:
    extends:
      file: docker-compose-adk.yml
      service: local-adk-agent
    volumes:
      - /home/user/repos:/repos #Update this to mount your local directories
